spring:
  application:
    name: sprint-boot-template
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/my_db
  jackson:
    property-naming-strategy: SNAKE_CASE  # 将驼峰自动转为蛇形
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
server:
  address: 127.0.0.1
  port: 8001
  servlet:
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
oss:
  endpoint: xx
  bucket-name: xx
  access-key: xx
  access-secret: xx
  expire-time: 3600
springdoc:
  swagger-ui:
    enabled: true

